services:
  php:
    build:
      context: ./services/php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        - ALPINE_MIRROR=${ALPINE_MIRROR}
    container_name: php
    restart: always
    volumes:
      - ./wwwroot/:/var/www/:rw
      - ./logs/php/:/var/log/php/:rw
      - ./data/composer/:/tmp/composer/:rw
      - ./services/php/php-${PHP_ENVIRONMENT}.ini:/usr/local/etc/php/php.ini:ro
      - ./services/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      - TZ=${TIME_ZONE}
    networks:
      monolith:
        ipv4_address: 172.16.24.11

  openresty:
    build:
      context: ./services/openresty
      args:
        - OPENRESTY_VERSION=${OPENRESTY_VERSION}
        - ALPINE_MIRROR=${ALPINE_MIRROR}
    container_name: openresty
    restart: always
    ports:
      - 0.0.0.0:${OPENRESTY_HTTP_PORT}:80
      - 0.0.0.0:${OPENRESTY_HTTPS_PORT}:443
    volumes:
      - ./wwwroot/:/var/www/:rw
      - ./logs/openresty/:/var/log/nginx/:rw
      - ./services/openresty/ssl/:/etc/nginx/ssl/:ro
      - ./services/openresty/conf.d/:/etc/nginx/conf.d/:ro
      - ./services/openresty/rewrite/:/etc/nginx/rewrite/:ro
      - ./services/openresty/openresty.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./services/openresty/fastcgi-php.conf:/usr/local/openresty/nginx/conf/fastcgi-php.conf:ro
      - ./services/openresty/fastcgi_params:/usr/local/openresty/nginx/conf/fastcgi_params:ro
    environment:
      - TZ=${TIME_ZONE}
    networks:
      monolith:
        ipv4_address: 172.16.24.21

  mariadb:
    image: mariadb:${DB_MARIADB_VERSION}
    container_name: mariadb
    restart: always
    volumes:
      - ./data/mariadb/:/var/lib/mysql/:rw
      - ./services/mariadb/mariadb.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./services/mariadb/scripts/:/docker-entrypoint-initdb.d/:ro
    environment:
      - TZ=${TIME_ZONE}
      - MARIADB_DATABASE=${DB_MARIADB_DATABASE_NAME}
      - MARIADB_USER_FILE=/run/secrets/mariadb-user-name
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb-user-pwd
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb-root-pwd
    secrets:
      - mariadb-root-pwd
      - mariadb-user-name
      - mariadb-user-pwd
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      monolith:
        ipv4_address: 172.16.24.31

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: phpmyadmin
    restart: always
    environment:
      - TZ=${TIME_ZONE}
      - PMA_ARBITRARY=0
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - UPLOAD_LIMIT=${PHPMYADMIN_UPLOAD_LIMIT}
    ports:
      - 0.0.0.0:${PHPMYADMIN_WEB_PORT}:80
    depends_on:
      - mariadb
    networks:
      monolith:
        ipv4_address: 172.16.24.41

  memcached:
    image: memcached:${MEMCACHED_VERSION}
    container_name: memcached
    restart: always
    networks:
      monolith:
        ipv4_address: 172.16.24.42

  redis:
    build:
      context: ./services/redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    container_name: redis
    restart: always
    volumes:
      - ./data/redis/:/data/:rw
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - TZ=${TIME_ZONE}
    networks:
      monolith:
        ipv4_address: 172.16.24.43

networks:
  monolith:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.24.0/24

secrets:
  mariadb-root-pwd:
    file: ./secrets/mariadb-root-pwd
  mariadb-user-name:
    file: ./secrets/mariadb-user-name
  mariadb-user-pwd:
    file: ./secrets/mariadb-user-pwd
